part_start = commandArgs(trailingOnly=TRUE)
setwd(part_start)
df_tcl<-paste0("structure               step5_input.psf\n",
               "coordinates             step5_input.pdb\n",
               "set temp                303.15;\n",
               "outputName              step7.1_production; # base name for output from this run\n",
               "# NAMD writes two files at the end, final coord and vel\n",
               "# in the format of first-dyn.coor and first-dyn.vel\n",
               "set inputname           step7_production;\n",
               "binCoordinates          $inputname.coor;    # coordinates from last run (binary)\n",
               "binVelocities           $inputname.vel;     # velocities from last run (binary)\n",
               "extendedSystem          $inputname.xsc;     # cell dimensions from last run (binary)\n",
               "restartfreq             5000;               # 5000 steps = every 10ps\n",
               "dcdfreq                 50000;\n",
               "dcdUnitCell             yes;                # the file will contain unit cell info in the style of\n",
               "# charmm dcd files. if yes, the dcd files will contain\n",
               "# unit cell information in the style of charmm DCD files.\n",
               "xstFreq                 5000;               # XSTFreq: control how often the extended systen configuration\n",
               "# will be appended to the XST file\n",
               "outputEnergies          5000;               # 5000 steps = every 10ps\n",
               "# The number of timesteps between each energy output of NAMD\n",
               "outputTiming            5000;               # The number of timesteps between each timing output shows\n",
               "# time per step and time to completion\n",
               "# Force-Field Parameters\n",
               "paraTypeCharmm          on;                 # We're using charmm type parameter file(s)\n",
               "# multiple definitions may be used but only one file per definition\n",
               "parameters              toppar/par_all36m_prot.prm\n",
               "parameters              toppar/par_all36_na.prm\n",
               "parameters              toppar/par_all36_carb.prm\n",
               "parameters              toppar/par_all36_lipid.prm\n",
               "parameters              toppar/par_all36_cgenff.prm\n",
               "parameters              toppar/par_interface.prm\n",
               "parameters              toppar/toppar_all36_nano_lig.str\n",
               "parameters              toppar/toppar_all36_nanolig_patch.str\n",
               "parameters              toppar/toppar_all36_synthetic_polymer.str\n",
               "parameters              toppar/toppar_all36_synthetic_polymer_patch.str\n",
               "parameters              toppar/toppar_all36_polymer_solvent.str\n",
               "parameters              toppar/toppar_water_ions.str\n",
               "parameters              toppar/toppar_dum_noble_gases.str\n",
               "parameters              toppar/toppar_ions_won.str\n",
               "parameters              toppar/toppar_all36_prot_arg0.str\n",
               "parameters              toppar/toppar_all36_prot_c36m_d_aminoacids.str\n",
               "parameters              toppar/toppar_all36_prot_fluoro_alkanes.str\n",
               "parameters              toppar/toppar_all36_prot_heme.str\n",
               "parameters              toppar/toppar_all36_prot_na_combined.str\n",
               "parameters              toppar/toppar_all36_prot_retinol.str\n",
               "parameters              toppar/toppar_all36_prot_modify_res.str\n",
               "parameters              toppar/toppar_all36_na_nad_ppi.str\n",
               "parameters              toppar/toppar_all36_na_rna_modified.str\n",
               "parameters              toppar/toppar_all36_lipid_archaeal.str\n",
               "parameters              toppar/toppar_all36_lipid_bacterial.str\n",
               "parameters              toppar/toppar_all36_lipid_cardiolipin.str\n",
               "parameters              toppar/toppar_all36_lipid_cholesterol.str\n",
               "parameters              toppar/toppar_all36_lipid_dag.str\n",
               "parameters              toppar/toppar_all36_lipid_inositol.str\n",
               "parameters              toppar/toppar_all36_lipid_lps.str\n",
               "parameters              toppar/toppar_all36_lipid_mycobacterial.str\n",
               "parameters              toppar/toppar_all36_lipid_miscellaneous.str\n",
               "parameters              toppar/toppar_all36_lipid_model.str\n",
               "parameters              toppar/toppar_all36_lipid_prot.str\n",
               "parameters              toppar/toppar_all36_lipid_sphingo.str\n",
               "parameters              toppar/toppar_all36_lipid_yeast.str\n",
               "parameters              toppar/toppar_all36_lipid_hmmm.str\n",
               "parameters              toppar/toppar_all36_lipid_detergent.str\n",
               "parameters              toppar/toppar_all36_lipid_ether.str\n",
               "parameters              toppar/toppar_all36_carb_glycolipid.str\n",
               "parameters              toppar/toppar_all36_carb_glycopeptide.str\n",
               "parameters              toppar/toppar_all36_carb_imlab.str\n",
               "parameters              toppar/toppar_all36_label_spin.str\n",
               "parameters              toppar/toppar_all36_label_fluorophore.str\n",
               "source                  step5_input.str\n",
               "# These are specified by CHARMM\n",
               "exclude                 scaled1-4           # non-bonded exclusion policy to use 'none,1-2,1-3,1-4,or scaled1-4'\n",
               "                                            # 1-2: all atoms pairs that are bonded are going to be ignored\n",
               "                                            # 1-3: 3 consecutively bonded are excluded\n",
               "                                            # scaled1-4: include all the 1-3, and modified 1-4 interactions\n",
               "                                            # electrostatic scaled by 1-4scaling factor 1.0\n",
               "                                            # vdW special 1-4 parameters in charmm parameter file.\n",
               "1-4scaling              1.0\n",
               "switching               on\n",
               "vdwForceSwitching       yes;                # New option for force-based switching of vdW\n",
               "# if both switching and vdwForceSwitching are on CHARMM force\n",
               "# switching is used for vdW forces.\n",
               
               "# You have some freedom choosing the cutoff\n",
               "cutoff                  12.0;               # may use smaller, maybe 10., with PME\n",
               "switchdist              10.0;               # cutoff - 2.\n",
               "                                            # switchdist - where you start to switch\n",
               "                                            # cutoff - where you stop accounting for nonbond interactions.\n",
               "                                            # correspondence in charmm:\n",
               "                                            # (cutnb,ctofnb,ctonnb = pairlistdist,cutoff,switchdist)\n",
               "pairlistdist            16.0;               # stores the all the pairs with in the distance it should be larger\n",
               "                                            # than cutoff( + 2.) \n",
               "stepspercycle           20;                 # 20 redo pairlists every ten steps\n",
               "pairlistsPerCycle       2;                  # 2 is the default \n",
               "                                            # cycle represents the number of steps between atom reassignments\n",
               "                                            # this means every 20/2=10 steps the pairlist will be updated\n",
               "                                            # Integrator Parameters\n",
               "timestep                2.0;                # fs/step\n",
               "rigidBonds              all;                # Bound constraint all bonds involving H are fixed in length\n",
               "nonbondedFreq           1;                  # nonbonded forces every step\n",
               "fullElectFrequency      1;                  # PME every step\n",
               "wrapWater               on;                 # wrap water to central cell\n",
               "wrapAll                 on;                 # wrap other molecules too\n",
               'if { $boxtype == "hexa" } {\n',
               "wrapNearest             on;                 # use for non-rectangular cells (wrap to the nearest image)\n",
               "} else {\n",
               "wrapNearest             off;                # use for non-rectangular cells (wrap to the nearest image)\n",
               "}\n",
               "# PME (for full-system periodic electrostatics)\n",
               "PME                     yes;\n",
               "PMEInterpOrder          6;                  # interpolation order (spline order 6 in charmm)\n",
               "PMEGridSpacing          1.0;                # maximum PME grid space / used to calculate grid size\n",
               "# Constant Pressure Control (variable volume)\n",
               "useGroupPressure        yes;                # use a hydrogen-group based pseudo-molecular viral to calcualte pressure and\n",
               "                                            # has less fluctuation, is needed for rigid bonds (rigidBonds/SHAKE)\n",
               "useFlexibleCell         yes;                # yes for anisotropic system like membrane\n",
               "useConstantRatio        yes;                # keeps the ratio of the unit cell in the x-y plane constant A=B\n",
               "langevinPiston          on;                 # Nose-Hoover Langevin piston pressure control\n",
               "langevinPistonTarget    1.01325;            # target pressure in bar 1atm = 1.01325bar \n",
               "langevinPistonPeriod    50.0;               # oscillation period in fs. correspond to pgamma T=50fs=0.05ps \n",
               "                                            # f=1/T=20.0(pgamma)\n",
               "langevinPistonDecay     25.0;               # oscillation decay time. smaller value correspons to larger random\n",
               "                                            # forces and increased coupling to the Langevin temp bath.\n",
               "                                            # Equall or smaller than piston period\n",
               "langevinPistonTemp      $temp;              # coupled to heat bath\n",
               "# Constant Temperature Control\n",
               "langevin                on;                 # langevin dynamics\n",
               "langevinDamping         1.0;                # damping coefficient of 1/ps (keep low)\n",
               "langevinTemp            $temp;              # random noise at this level\n",
               "langevinHydrogen        off;                # don't couple bath to hydrogens\n",
               "# run\n",
               "numsteps                500000;             # run stops when this step is reached\n",
               "run                     500000;             # 1ns")
write.table(df_tcl,paste0(part_start,"namd/step7.",1,"_production.inp"),row.names=F,col.names=F,quote = F)
for (i in 1:999) {
  
  df_tcl<-paste0("structure               step5_input.psf\n",
                 "coordinates             step5_input.pdb\n",
                 "set temp                303.15;\n",
                 "outputName              step7.",i+1,"_production; # base name for output from this run\n",
                 "# NAMD writes two files at the end, final coord and vel\n",
                 "# in the format of first-dyn.coor and first-dyn.vel\n",
                 "set inputname           step7.",i,"_production;\n",
                 "binCoordinates          $inputname.coor;    # coordinates from last run (binary)\n",
                 "binVelocities           $inputname.vel;     # velocities from last run (binary)\n",
                 "extendedSystem          $inputname.xsc;     # cell dimensions from last run (binary)\n",
                 "restartfreq             5000;               # 5000 steps = every 10ps\n",
                 "dcdfreq                 50000;\n",
                 "dcdUnitCell             yes;                # the file will contain unit cell info in the style of\n",
                 "# charmm dcd files. if yes, the dcd files will contain\n",
                 "# unit cell information in the style of charmm DCD files.\n",
                 "xstFreq                 5000;               # XSTFreq: control how often the extended systen configuration\n",
                 "# will be appended to the XST file\n",
                 "outputEnergies          5000;               # 5000 steps = every 10ps\n",
                 "# The number of timesteps between each energy output of NAMD\n",
                 "outputTiming            5000;               # The number of timesteps between each timing output shows\n",
                 "# time per step and time to completion\n",
                 "# Force-Field Parameters\n",
                 "paraTypeCharmm          on;                 # We're using charmm type parameter file(s)\n",
                 "# multiple definitions may be used but only one file per definition\n",
                 "parameters              toppar/par_all36m_prot.prm\n",
                 "parameters              toppar/par_all36_na.prm\n",
                 "parameters              toppar/par_all36_carb.prm\n",
                 "parameters              toppar/par_all36_lipid.prm\n",
                 "parameters              toppar/par_all36_cgenff.prm\n",
                 "parameters              toppar/par_interface.prm\n",
                 "parameters              toppar/toppar_all36_nano_lig.str\n",
                 "parameters              toppar/toppar_all36_nanolig_patch.str\n",
                 "parameters              toppar/toppar_all36_synthetic_polymer.str\n",
                 "parameters              toppar/toppar_all36_synthetic_polymer_patch.str\n",
                 "parameters              toppar/toppar_all36_polymer_solvent.str\n",
                 "parameters              toppar/toppar_water_ions.str\n",
                 "parameters              toppar/toppar_dum_noble_gases.str\n",
                 "parameters              toppar/toppar_ions_won.str\n",
                 "parameters              toppar/toppar_all36_prot_arg0.str\n",
                 "parameters              toppar/toppar_all36_prot_c36m_d_aminoacids.str\n",
                 "parameters              toppar/toppar_all36_prot_fluoro_alkanes.str\n",
                 "parameters              toppar/toppar_all36_prot_heme.str\n",
                 "parameters              toppar/toppar_all36_prot_na_combined.str\n",
                 "parameters              toppar/toppar_all36_prot_retinol.str\n",
                 "parameters              toppar/toppar_all36_prot_modify_res.str\n",
                 "parameters              toppar/toppar_all36_na_nad_ppi.str\n",
                 "parameters              toppar/toppar_all36_na_rna_modified.str\n",
                 "parameters              toppar/toppar_all36_lipid_archaeal.str\n",
                 "parameters              toppar/toppar_all36_lipid_bacterial.str\n",
                 "parameters              toppar/toppar_all36_lipid_cardiolipin.str\n",
                 "parameters              toppar/toppar_all36_lipid_cholesterol.str\n",
                 "parameters              toppar/toppar_all36_lipid_dag.str\n",
                 "parameters              toppar/toppar_all36_lipid_inositol.str\n",
                 "parameters              toppar/toppar_all36_lipid_lps.str\n",
                 "parameters              toppar/toppar_all36_lipid_mycobacterial.str\n",
                 "parameters              toppar/toppar_all36_lipid_miscellaneous.str\n",
                 "parameters              toppar/toppar_all36_lipid_model.str\n",
                 "parameters              toppar/toppar_all36_lipid_prot.str\n",
                 "parameters              toppar/toppar_all36_lipid_sphingo.str\n",
                 "parameters              toppar/toppar_all36_lipid_yeast.str\n",
                 "parameters              toppar/toppar_all36_lipid_hmmm.str\n",
                 "parameters              toppar/toppar_all36_lipid_detergent.str\n",
                 "parameters              toppar/toppar_all36_lipid_ether.str\n",
                 "parameters              toppar/toppar_all36_carb_glycolipid.str\n",
                 "parameters              toppar/toppar_all36_carb_glycopeptide.str\n",
                 "parameters              toppar/toppar_all36_carb_imlab.str\n",
                 "parameters              toppar/toppar_all36_label_spin.str\n",
                 "parameters              toppar/toppar_all36_label_fluorophore.str\n",
                 "source                  step5_input.str\n",
                 "# These are specified by CHARMM\n",
                 "exclude                 scaled1-4           # non-bonded exclusion policy to use 'none,1-2,1-3,1-4,or scaled1-4'\n",
                 "                                            # 1-2: all atoms pairs that are bonded are going to be ignored\n",
                 "                                            # 1-3: 3 consecutively bonded are excluded\n",
                 "                                            # scaled1-4: include all the 1-3, and modified 1-4 interactions\n",
                 "                                            # electrostatic scaled by 1-4scaling factor 1.0\n",
                 "                                            # vdW special 1-4 parameters in charmm parameter file.\n",
                 "1-4scaling              1.0\n",
                 "switching               on\n",
                 "vdwForceSwitching       yes;                # New option for force-based switching of vdW\n",
                 "# if both switching and vdwForceSwitching are on CHARMM force\n",
                 "# switching is used for vdW forces.\n",
                 
                 "# You have some freedom choosing the cutoff\n",
                 "cutoff                  12.0;               # may use smaller, maybe 10., with PME\n",
                 "switchdist              10.0;               # cutoff - 2.\n",
                 "                                            # switchdist - where you start to switch\n",
                 "                                            # cutoff - where you stop accounting for nonbond interactions.\n",
                 "                                            # correspondence in charmm:\n",
                 "                                            # (cutnb,ctofnb,ctonnb = pairlistdist,cutoff,switchdist)\n",
                 "pairlistdist            16.0;               # stores the all the pairs with in the distance it should be larger\n",
                 "                                            # than cutoff( + 2.) \n",
                 "stepspercycle           20;                 # 20 redo pairlists every ten steps\n",
                 "pairlistsPerCycle       2;                  # 2 is the default \n",
                 "                                            # cycle represents the number of steps between atom reassignments\n",
                 "                                            # this means every 20/2=10 steps the pairlist will be updated\n",
                 "                                            # Integrator Parameters\n",
                 "timestep                2.0;                # fs/step\n",
                 "rigidBonds              all;                # Bound constraint all bonds involving H are fixed in length\n",
                 "nonbondedFreq           1;                  # nonbonded forces every step\n",
                 "fullElectFrequency      1;                  # PME every step\n",
                 "wrapWater               on;                 # wrap water to central cell\n",
                 "wrapAll                 on;                 # wrap other molecules too\n",
                 'if { $boxtype == "hexa" } {\n',
                 "wrapNearest             on;                 # use for non-rectangular cells (wrap to the nearest image)\n",
                 "} else {\n",
                 "wrapNearest             off;                # use for non-rectangular cells (wrap to the nearest image)\n",
                 "}\n",
                 "# PME (for full-system periodic electrostatics)\n",
                 "PME                     yes;\n",
                 "PMEInterpOrder          6;                  # interpolation order (spline order 6 in charmm)\n",
                 "PMEGridSpacing          1.0;                # maximum PME grid space / used to calculate grid size\n",
                 "# Constant Pressure Control (variable volume)\n",
                 "useGroupPressure        yes;                # use a hydrogen-group based pseudo-molecular viral to calcualte pressure and\n",
                 "                                            # has less fluctuation, is needed for rigid bonds (rigidBonds/SHAKE)\n",
                 "useFlexibleCell         yes;                # yes for anisotropic system like membrane\n",
                 "useConstantRatio        yes;                # keeps the ratio of the unit cell in the x-y plane constant A=B\n",
                 "langevinPiston          on;                 # Nose-Hoover Langevin piston pressure control\n",
                 "langevinPistonTarget    1.01325;            # target pressure in bar 1atm = 1.01325bar \n",
                 "langevinPistonPeriod    50.0;               # oscillation period in fs. correspond to pgamma T=50fs=0.05ps \n",
                 "                                            # f=1/T=20.0(pgamma)\n",
                 "langevinPistonDecay     25.0;               # oscillation decay time. smaller value correspons to larger random\n",
                 "                                            # forces and increased coupling to the Langevin temp bath.\n",
                 "                                            # Equall or smaller than piston period\n",
                 "langevinPistonTemp      $temp;              # coupled to heat bath\n",
                 "# Constant Temperature Control\n",
                 "langevin                on;                 # langevin dynamics\n",
                 "langevinDamping         1.0;                # damping coefficient of 1/ps (keep low)\n",
                 "langevinTemp            $temp;              # random noise at this level\n",
                 "langevinHydrogen        off;                # don't couple bath to hydrogens\n",
                 "# run\n",
                 "numsteps                500000;             # run stops when this step is reached\n",
                 "run                     500000;             # 1ns")
  write.table(df_tcl,paste0(part_start,"namd/step7.",i+1,"_production.inp"),row.names=F,col.names=F,quote = F)
}
df_namd<-data.frame(matrix(ncol=2,nrow = 1007))
colnames(df_namd)<-c("comand","conf")
df_namd$comand<-"run_namd"
a<-c( paste0("step6.",c(1:6),"_equilibration.inp > step6.",c(1:6),"_equilibration.out"),
      "step7_production.inp > step7_production.out",
      paste0("step7.",c(1:1000),"_production.inp > step7.",c(1:1000),"_production.out"))
df_namd$conf<-a
df_namd_add<-data.frame(matrix(ncol=2,nrow = 1))
colnames(df_namd_add)<-c("comand","conf")
df_namd_add$comand<-paste0("cd ",part_start,"namd")
df_namd<-rbind(df_namd_add,df_namd)
write.table(df_namd,paste0("run_namd.txt"),sep = " ",row.names = F,col.names = F,quote = F,na = "")
